### ISSUE TITLE
Improve LHS for healthy thinking pages

### ISSUE THREAD

**Issue by jindaliiita** [hlxsites/sunstar#136]
[lhs_score_healthy_thinking.csv](https://github.com/hlxsites/sunstar/files/12883602/lhs_score_healthy_thinking.csv)

**Comment by jindaliiita** [comment]
@sdmcraft This seems to be related to https://github.com/hlxsites/sunstar/pull/364
I have checked on some pages and with you PR LHS significantly improves to 99 - 100.

**Comment by sdmcraft** [comment]
Closing this since #364 is merged. If needed, we can repen with more details about specific pages which may be reporting low LHS.
