### ISSUE TITLE
Press Contact and Download Section

### ISSUE THREAD

**Issue by jindaliiita** [hlxsites/sunstar#141]
Original Implementation
<img width="1728" alt="Screenshot 2023-10-13 at 4 34 20 PM" src="https://github.com/hlxsites/sunstar/assets/12638407/8789b7fb-44a2-44cf-8fef-142bb02924d5">

Franklin Implementation
<img width="1728" alt="Screenshot 2023-10-13 at 4 35 10 PM" src="https://github.com/hlxsites/sunstar/assets/12638407/6f9720b0-9530-4713-8051-b11ab4f56eec">

Original URL - https://www.sunstar.com/newsroom/event/38th-ciosp-brazil/
URL - https://main--sunstar--hlxsites.hlx.page/newsroom/38th-ciosp-brazil

@ehrro Can you please check this.
There is one section present in each news page **Press Contact** and **Download Center**.  In original implementation its a column block but for simplicity i have kept it as a normal text (As mentioned by you earlier regarding the news articles). If you think it's OK then we can go ahead otherwise we have to add a new variant of columns block here.

**Comment by ehrro** [comment]
Hello @jindaliiita I am good with your version. Please go ahead. Thank you.
