### ISSUE TITLE
Consumer Heath & Beauty Page

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#163]
1. Remove the left padding on the hero text wrapper:
![image](https://github.com/hlxsites/sunstar/assets/1226479/9d7f0ba3-a6b5-469c-8280-db1181f4dd06)

2. The image on mobile should different aspect ratio: left current, right franklin
![image](https://github.com/hlxsites/sunstar/assets/1226479/58b5c3de-a336-4fd9-8d9c-5b15e1e332ad)

3. Missing spacing after the Toc menu
![image](https://github.com/hlxsites/sunstar/assets/1226479/3e74172a-2bcf-441d-bae1-f422050f9f39)

4. I am waiting on GH ticket #142 to comment on the heading styling.

**Comment by JiangLong2019** [comment]
Hi @ehrro 1, 2 and 3 have been fixed, please help to check. If it's ok, I'll merge it.

https://issue-163--sunstar--hlxsites.hlx.page/brands/consumer-health-beauty

**Comment by ehrro** [comment]
It's all good @JiangLong2019 you can merge.

**Comment by JiangLong2019** [comment]
@ehrro Thanks for confirming!
