### ISSUE TITLE
Columns Component

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#166]
I noticed that the columns component on Sunstar Engineering has margin bottom top properties but not on Sunstar.com.

![image](https://github.com/hlxsites/sunstar/assets/1226479/2f22f85b-0370-4b1c-b9ac-f5d165217340)

For example on the following page: https://main--sunstar--hlxsites.hlx.live/brands the space is too narrow between columns and the section itself.

Can we set it as it was for Sunstar Engineering please. Thanks.

**Comment by sdmcraft** [comment]
This was removed for the history page via https://github.com/hlxsites/sunstar/pull/121 by @dnbute 
I think there this big bottom margin was looking a bit big. @ehrro , would it be ok to have that bi margin there? If yes, we can reinstate that margin. Else please suggest a common margin bottom that can be used globally.

**Comment by ehrro** [comment]
We can use the same logic as we used for sunstar-engineering.com. If we create 1 column table with several rows then apply small margin if there is 1 table for row then apply the big margin. What do you think?

**Comment by sdmcraft** [comment]
> We can use the same logic as we used for sunstar-engineering.com. If we create 1 column table with several rows then apply small margin if there is 1 table for row then apply the big margin. What do you think?

Yeah, I'd rather have a single column block with multiple rows instead of multiple column blocks in the Word doc.
@JiangLong2019 , looks like you worked on this page. Do you think it is possible to combine multiple columns blocks here into one here. That'd take care of styling and also be much easier for authors.

**Comment by JiangLong2019** [comment]
Hi @ehrro, I changed the styling, can you please help to check if it's ok?
https://issue-166--sunstar--hlxsites.hlx.page/brands

@sdmcraft @dnbute Let me know if this change affect your pages.

**Comment by dnbute** [comment]
It kinda messes with this 
https://issue-166--sunstar--hlxsites.hlx.page/about/history
<img width="787" alt="Screenshot 2023-10-25 at 10 31 39" src="https://github.com/hlxsites/sunstar/assets/44490413/5567d293-b749-4247-aaab-408499294f6d">

But I think a `no-bottom-margin` variant would do the trick, I have an open PR where I can add it

**Comment by JiangLong2019** [comment]
@dnbute Ops, thanks for sharing that. I agree, it would be great  if a new variant can resolve the problem.

**Comment by sdmcraft** [comment]
How about you add the text below the columns block to the block itself as another row in it spanning across 2 columns?

**Comment by dnbute** [comment]
<img width="699" alt="Screenshot 2023-10-26 at 10 42 56" src="https://github.com/hlxsites/sunstar/assets/44490413/85ee0d8e-c599-41be-9512-052cb7d8d44e">

So this is what I managed to get by adding a `:last-of-type` to the css that adds `margin-bottom: 7.5rem`, and it looks good, apart from the pretty big margin at the bottom; so basically I guess I just moved the problematic margin a bit lower unfortunately :(

**Comment by sdmcraft** [comment]
would it help if you put the grey shade in the block instead of the section?

**Comment by dnbute** [comment]
I think this is the only instance where a `columns` block is used like this, regardless of how I author this page we'll need @JiangLong2019's changes; I'll wait for the PR to take a closer look at what changed exactly and then I'll figure something out since I think it'll be easier that way, sounds good?

**Comment by ehrro** [comment]
The spacing is now good. I have one more request is to horizontally align the image and the content on the right.
![image](https://github.com/hlxsites/sunstar/assets/1226479/e71872ad-a5cd-44ef-a5f3-1c1054c14d54)

**Comment by ehrro** [comment]
In addition to this I also opened another ticket to address the issue on mobile when putting margin on a container with 100% width.

![image](https://github.com/hlxsites/sunstar/assets/1226479/185f9afe-cc43-4eef-9a6d-f7ca1b32a6fb)


You can fix that be either deleting the width here:

![image](https://github.com/hlxsites/sunstar/assets/1226479/5c15170d-894c-4c76-b0fa-3b7232699c78)

Or using padding instead of margin:
![image](https://github.com/hlxsites/sunstar/assets/1226479/91bce4d4-c4c5-4c4a-b7b7-9fd4a9e485b0)

Thank you.

**Comment by JiangLong2019** [comment]
@ehrro Thanks for the feedback. I've addressed all the above, please help to check.
https://issue-166--sunstar--hlxsites.hlx.page/brands

@dnbute Sure, let's discuss. All changes are on branch "issue-166". I think it's easy to merge because only few lines had been changed, but we need to make sure it won't affect other pages.

**Comment by ehrro** [comment]
Hello @JiangLong2019 it's good for me.

**Comment by JiangLong2019** [comment]
Thanks @ehrro
