### ISSUE TITLE
Tags Block change

### ISSUE THREAD

**Issue by jindaliiita** [hlxsites/sunstar#167]
1. For tag home page, tags block should fetch each and every tag from the tags sheet corresponding to the language selected. Don't need to add metadata in this case on the page.
2. At other places we fetch details (tag key) from the metadata and get name from the tags sheet.

URL creation logic will be in the code
tag key --> immune-system
url --> /healthy-thinking/tag?feed-tags=immune-system
tag key --> immune-system-jp
url --> /jp/healthy-thinking/tag?feed-tags=immune-system-jp

Changes will be done after the discussion between @sdmcraft and @ehrro

**Comment by sdmcraft** [comment]
Few suggestions:

1. Introduce an `all` variant of `tags` block whicvh fetches all the tags.
2. Keeps a separate tags.xlsx which has all the tags with the following columns, `id` ,  `type`, `url`
3. Keep the tag names as usual in `placeholders.xlsx`
4. Introduce a `fetchTags` method in `scripts.js` to fetch tags. It can take `type` , `id`, `locale` as optional parameters.
5. The above method should return tuples containing `id, type, url, name`.
6. All word docs which have `tags` in metadata should be re-imported to have the `id` of the tag in this metadata.
7. All word docs that need to show all the tags, should remove `tags` metadata and instead use the `tags(all)` block to show all the tags.
