### ISSUE TITLE
Default Typography styling

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#171]
As discussed during one of our sync up meetings I would like to apply default styling to typography elements such as:

h1 to h5, p, ol, ul, blockquote etc..

I will create a page called typography and will add all the elements that should be styled.

**Comment by ehrro** [comment]
Hello those are the spacing generic for the typography:

h1 margin: 70px 0 40px
h2 margin: 56px 0 32px
h3 margin: 40px 0 16px
h4 margin: 32px 0 8px
p margin: 0 0 24px 0
ul, ol margin: 0 0 24px 0 padding: 0 0 0 28px
li margin: 12px 0 padding: 0 0 0 8px

I created this page to track the implementation and see if there is a need to adjust the default style.
https://main--sunstar--hlxsites.hlx.page/typography

**Comment by ehrro** [comment]
@sdmcraft

**Comment by sdmcraft** [comment]
I guess this may need a few adjustments at places which apply their own typography. Let's see what the automated visual tests for this PR may throw up.

**Comment by ehrro** [comment]
Yes there are few blocks/components that use UL, LI so I will first create a PR to get all the elements then I will go and override the default style for these.
