### ISSUE TITLE
Only article pages should have tag metadata

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/sunstar#173]
Only article pages should have tag metadata.
Top level pages such as https://main--sunstar--hlxsites.hlx.page/healthy-thinking/holistic-health-care should nt be tagged.
Instead they should show all the tags for browsing purposes.

![image](https://github.com/hlxsites/sunstar/assets/1191451/cb7ee695-9e85-4b93-8990-668c21a7e00e)

**Comment by sdmcraft** [comment]
@ehrro , please let know if the understanding in the issue description is correct.

**Comment by ehrro** [comment]
Hello @sdmcraft yes correct.

**Comment by jindaliiita** [comment]
Completed via https://github.com/hlxsites/sunstar/pull/209
