### ISSUE TITLE
About > History > Captions

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#196]
The image captions are in Italic. Can you please remove Italic style? I see that we need to use Italic in word to tag them as captions but I believe we can set a different html tag.

![image](https://github.com/hlxsites/sunstar/assets/1226479/1e131a24-429d-4ff0-90af-735f8ccfe348)

I am also not sure about the font color used here. It doesn't look like it has a good contrast ratio. On Sunstar Engineering we used the following color for captions:
![image](https://github.com/hlxsites/sunstar/assets/1226479/9c3534aa-3a90-4ab3-8ab9-4fd905a66d45)

Thank you.

**Comment by dnbute** [comment]
Hi @ehrro, would you like ALL captions to not be italic, or just these on the history page?

**Comment by ehrro** [comment]
Hello @dnbute yes all captions shouldn't be italic.

Regarding 90 year journey, yes I think we agreed together on that :)

Thank you Dragos

**Comment by dnbute** [comment]
>Regarding 90 year journey, yes I think we agreed together on that :)

Yeah, but you said you'll provide a picture that's higher resolution
