### ISSUE TITLE
Document process to add new tag/category and adding to page metadata

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/sunstar#217]

**Comment by jindaliiita** [comment]
Added all the details in below doc and page
https://adobe.sharepoint.com/sites/HelixProjects/_layouts/15/doc.aspx?sourcedoc={06ef67e1-e9d6-4143-a596-3ba21bbd2383}&action=edit

https://main--sunstar--hlxsites.hlx.live/sidekick/blocks/tags-categories-doc

Block Library ->
https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/tags-categories-doc&index=0
https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/tags-categories-doc&index=1

So, closing this issue
