### ISSUE TITLE
Brands Page

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#220]
The non-singleton-img class is buggy.

![image](https://github.com/hlxsites/sunstar/assets/1226479/ae10f13c-c8d0-47b4-bc4c-ac83287fff87)
![image](https://github.com/hlxsites/sunstar/assets/1226479/53cb0027-d477-42f3-855f-104e450ed0fa)

If we change margin to padding and add box-sizing: border-box; it fixes the issue.

![image](https://github.com/hlxsites/sunstar/assets/1226479/8ace2a50-ca28-439e-81e7-29e84aecac4e)

**Comment by JiangLong2019** [comment]
Address this by #166
