### ISSUE TITLE
Nav

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#221]
There is an overflow: scroll while hovering the main nav items:

![image](https://github.com/hlxsites/sunstar/assets/1226479/33d30d58-6c93-449b-bbb3-19e3723300fc)

On mobile the line height is set to 21px for 3 level nav items:

![image](https://github.com/hlxsites/sunstar/assets/1226479/fa143406-f224-4b99-8727-5291d5a595b3)

setting it to 2.75rem (same as the height) fixes the issue.

**Comment by ehrro** [comment]
sorry I didn't paste the right screenshot for the first issue. Here it is:
![image](https://github.com/hlxsites/sunstar/assets/1226479/12fb837b-a67b-4a2f-be44-a7fec21f2d41)

**Comment by hparwani2** [comment]
@ehrro I can't exactly spot the differences, let's discuss this in scrum.

**Comment by ehrro** [comment]
Hello @hparwani2 the issue is that when you open the dropdown it add scroll on the x axis (the dropdown container is going outside the viewport).
