### ISSUE TITLE
Auto generate meta tags for Tag page

### ISSUE THREAD

**Issue by JiangLong2019** [hlxsites/sunstar#229]
Since the tag page is only one static page with request query parameters, some meta tags in the head will be generated automatically. The following shows the specification.

1. Auto-generate meta tags:

| Meta tag  | Description |
| ------------- | ------------- |
| document title | tag title; show it as the title of healthy-thinking detail page list on the page |
| og:title | tag title |
| twitter:title | tag title |
| canonical | current page url |
| og:url | current page url |
| og:image | the image of the first healthy-thinking detail page in the list(keep same logic with original site) |
| og:image:secure_url | the image of the first healthy-thinking detail page in the list(keep same logic with original site) |
| twitter:image | the image of the first healthy-thinking detail page in the list(keep same logic with original site) |

2. Show tag title as breadcrumb title.

3. Non auto-generate meta tags:

| Meta tag  | Description |
| ------------- | ------------- |
| description | it doesn't exist in original site |
| og:description | it doesn't exist in original site |
| twitter:description | it doesn't exist in original site |
| twitter:card | can be set in page metadata |

**Comment by JiangLong2019** [comment]
@sdmcraft @jindaliiita I summarized the auto-generate meta tag for the tag page, let me know if you have any questions.

**Comment by jindaliiita** [comment]
I have just one doubt over having single page for tags. will it create any issue on the SEO side.
And also how user will be able to find particular tag page in search ?

**Comment by JiangLong2019** [comment]
@jindaliiita We discussed this on https://cq-dev.slack.com/archives/C058KBHLBGR/p1697600269581489. Seems the single page can bring more benefits, such as reduce authoring effort, uniform tag data, etc...
CC: @sdmcraft
