### ISSUE TITLE
Extend Career carousel block to display carousel as card. (for Research page)

### ISSUE THREAD

**Issue by RitwikSrivastava** [hlxsites/sunstar#231]

**Comment by sdmcraft** [comment]
May we should also generalize its name to "cards-carousel" .
@bosschaert wdyt?

**Comment by bosschaert** [comment]
The devil is in the detail 😉 
I'm not 100% sure the career carousel can easily be generalised as it's really tailored to its current functionality shape and behaviour.
However, if you think it can be generalised I'm totally happy to generalise the name too.

**Comment by sdmcraft** [comment]
The thought I had was to have the career-carousel be either driven off the index (which it is right now) or be provided a markup and then just use that. Intent is to reuse its rendering logic and styles. To be safer, we can create a copy of it as a new block, a deprecate this one once we have the new one working ok.
