### ISSUE TITLE
Table block - fix regression issue with heading styles

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/sunstar#233]
Page: https://main--sunstar--hlxsites.hlx.page/research/literature

Current state:
![image](https://github.com/hlxsites/sunstar/assets/129100763/9aa74578-7e80-452b-8198-161a9523c270)

Expected state:
![image](https://github.com/hlxsites/sunstar/assets/129100763/bb94391c-fe06-4bb6-82ec-8990ba628be6)

**Comment by sdmcraft** [comment]
@ehrro , this may relate to some of the global styling updates we did (like the heading font size and paddings). Do you think we need block specific overrides here or the global styles are ok.

**Comment by ehrro** [comment]
It looks like it has been fixed :) Yes we should always override the global styles.
