### ISSUE TITLE
Careers Page

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#236]
1. Cards Block, remove h2 max-width property:
![image](https://github.com/hlxsites/sunstar/assets/1226479/057fe327-5e54-4a4f-ac3a-ef3c3ecc893a)

2. Cards Block, set margin-top to 0 on h4 element on mobile only
![image](https://github.com/hlxsites/sunstar/assets/1226479/2b5692e8-b4d5-4fab-afdf-c49910df0838)

3. Cards Block, set margin-top to 0 on cards img element on mobile only
![image](https://github.com/hlxsites/sunstar/assets/1226479/fcecab5a-ba79-49a8-bc08-7789f19bfec7)

4. Overlapping content, override global h2 style, remove margin top on h2.
![image](https://github.com/hlxsites/sunstar/assets/1226479/6aa05c18-c7ce-44c1-9cd4-8f95b0f25363)

5. Columns block, make sure the button content is display inline-block.
![image](https://github.com/hlxsites/sunstar/assets/1226479/2298cec6-ad88-43f9-9df7-95c84af45c99)

6. Career apply block, override global h2 style, remove margin top on h2.
![image](https://github.com/hlxsites/sunstar/assets/1226479/14d2c1b2-8a22-48f4-87df-6901b1cfe357)

7. Bg Primary or Centered section, override global h2, h3 etc.. styles, replace margin-bottom: 0 to margin-top: 0
![image](https://github.com/hlxsites/sunstar/assets/1226479/7fcb3593-8071-47e0-9f49-de12119a5b45)

8. Section missing padding: 1 rem on mobile.
![image](https://github.com/hlxsites/sunstar/assets/1226479/57c01eea-e077-41fe-aba8-f28c119d832c)

9. Cards container not centered.
![image](https://github.com/hlxsites/sunstar/assets/1226479/e19b7ef2-363e-4f7d-9f73-f7cf8cc26bbd)

10. Card content, only image should be centered not the rest. To fix that you can set the parent to 100% width and create a selector for all except the picture element and set the width to 100%.

.career-carousel .career-card a > :not(picture) {
    width: 100%;
}

![image](https://github.com/hlxsites/sunstar/assets/1226479/b37dd742-7e69-47bc-b064-b38f3f185025)

**Comment by bosschaert** [comment]
@ehrro re point 5, what visual change would you like to create with this?

**Comment by ehrro** [comment]
The current is looking like this:
![image](https://github.com/hlxsites/sunstar/assets/1226479/8dc440d5-7bae-4e47-b67c-d5faab27e6c7)

I want to make sure the text will take all the available space inside the button

**Comment by ehrro** [comment]
If you look at my inspector selection and at the cards you can see that it goes outside the container therefore it's not centered.

Here is the same screenshot on sunstar.com
![image](https://github.com/hlxsites/sunstar/assets/1226479/8cbd5642-28a8-4f9a-ada6-dfc70676f3e5)

**Comment by bosschaert** [comment]
> I want to make sure the text will take all the available space inside the button

Thanks! It seems that `display: inline` has the correct effect. `inline-block` doesn't do it...

**Comment by ehrro** [comment]
I think it's because of the parent element. It has a width set to 11rem. If you remove it it fixes the issue.
