### ISSUE TITLE
Learn more

### ISSUE THREAD

**Issue by jindaliiita** [hlxsites/sunstar#238]
Original - https://www.sunstar.com/jp/newsroom/news/20230901/
<img width="1728" alt="Screenshot 2023-10-30 at 2 53 58 PM" src="https://github.com/hlxsites/sunstar/assets/12638407/005d16a4-3f1d-4bfa-82aa-9f9f7f786984">

Franklin - https://main--sunstar--hlxsites.hlx.page/jp/newsroom/20230901
<img width="1728" alt="Screenshot 2023-10-30 at 2 53 46 PM" src="https://github.com/hlxsites/sunstar/assets/12638407/cc8604ea-3ff3-4583-8b76-4b2495436363">

@ehrro Can you please check if the franklin implementation for the learn more seems to be OK to you. I have made it simple

**Comment by ehrro** [comment]
Hello @jindaliiita yes all good like this.
