### ISSUE TITLE
Internal vs External and PDF links logic

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#239]
Hello can you please apply the same logic as we did for sunstar-engineering.com for the internal, external and pdf links?

- All external and PDF links should open in a new window

Thanks.

**Comment by sdmcraft** [comment]
@ehrro , I think that should already work. This is [handled here](https://github.com/hlxsites/sunstar/blob/31e2d7655500761b9f8c4d3dc2baffe63e32958a/scripts/scripts.js#L257-L261). 
If there's an instance where it is not working as expected, could you please share?

**Comment by jindaliiita** [comment]
Yes its already handled via https://github.com/hlxsites/sunstar/pull/122.

**Comment by ehrro** [comment]
It's doesn't work.

If you go to this page:
https://main--sunstar--hlxsites.hlx.live/about/global-network

Try to access an external link, it will still open in the same window :(

**Comment by sdmcraft** [comment]
Indeed you are right. The mentioned code does come in play and add the `target=_blank` attribute but then something else ends up removes that attribute. This needs to be further investigated.
