### ISSUE TITLE
Above the fold feed block degrades LCP

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/sunstar#242]
Feedblock feches the index to render items. For uncached scenarios, this can degrade the LCP. E.g..
https://main--sunstar--hlxsites.hlx.live/jp/_drafts/satyam/test

**Comment by dnbute** [comment]
I tried to fix this by only getting the first `Count` items from the query but unfortunately this won't guarantee that those items will also include what your feed block is looking for (correct category, tag w/e), in case anybody else also had the same idea

**Comment by sdmcraft** [comment]
> I tried to fix this by only getting the first `Count` items from the query but unfortunately this won't guarantee that those items will also include what your feed block is looking for (correct category, tag w/e), in case anybody else also had the same idea

Yes true, there might be cases where the query needs to reach beyond the first index page to gather the results.
