### ISSUE TITLE
Fix renovate configuration

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/sunstar#287]
Currently renovate creates a branch name like `renovate/stylelint-15.x` which has forward slash `/` and `.` . This creates an invalid test url since test urls are created using in the branch name This ticket is logged to fix this problem.

**Comment by sdmcraft** [comment]
@tripodsan , would you know how to address this? I checked [across project repos](https://github.com/search?q=org%3Ahlxsites%20.renovaterc.json&type=code) and found this configured as 
```
{
  "extends": ["github>adobe/helix-shared"]
}
```
Should the same be setup here? 
/cc @dnbute

**Comment by dnbute** [comment]
>yes, this is wrong. don't extend from helix-shared.
see https://github.com/adobe/aem-boilerplate/blob/main/.renovaterc.json

This indeed works, but we want the PRs the bot creates to actually be mergeable, for that we need test urls from the branch, for the URLs we need the branches to not contain `.`, the recommended config creates such branches with `.`

Won't the change to the boilerplate make it so all new PRs from the renovate bot on every new project require admin override to be merged?

**Comment by sdmcraft** [comment]
> we need the branches to not contain `.`, the recommended config creates such branches with `.`

Yes and also forward slash`/` in branch names are problematic. Perhaps the special branch naming requirements that we have (due to they being used to test urls), should be accommodated in the shared template for renovate.

**Comment by dnbute** [comment]
@tripodsan any thoughts on our previous comments?

**Comment by tripodsan** [comment]
you can add:
```
"branchPrefix": "renovate-",
```

**Comment by dnbute** [comment]
We can, yes, but it will create stuff like `renovate-whatever.1.x` which will break the test urls

**Comment by tripodsan** [comment]
you  can set the branch name to whatever you want:
https://docs.renovatebot.com/configuration-options/#branchname

for example in https://github.com/adobe/mdast-util-gridtables/pull/82
it's just `renovate external fixes`

**Comment by dnbute** [comment]
I think the overarching question is, should we also update the boilerplate (I think we should), and if so,  could we come up with a common config for all projects i.e. `branchPrefix`, `branchTopic`, `prBodyNotes` etc

We have this [PR](https://github.com/hlxsites/sunstar/pull/275) open on our side, we could test stuff here and then merge them to the boilerplate as well

**Comment by sdmcraft** [comment]
@dnbute , resolving this as it has been fixed. Please open an issue in bolierplate if you think this should be added in it.
