### ISSUE TITLE
Automatically inject breadcrumbs on pages

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/sunstar#292]
Breadcrumbs are present across all pages. So its an unnecessary overhead for author to explicitly add them to each page and it introduces chances of manual error if the author fails to add it or add it incorrectly. Ideally the breadcrumb block should be automatically added to a page. For cases where its already present, the automatic addition can be skipped.

**Comment by sdmcraft** [comment]
@jindaliiita wdyt?

**Comment by jindaliiita** [comment]
How we will determine on which page we have to show the breadcrumb. For eg. on home page its not present.
I am not sure if there is any other page present where breadcrumb is not present.
We can definitely have some logic to auto inject breadcrumb if we have defined set of pages where breadcrumb is not present.

**Comment by mkbansal1** [comment]
We can use below login

- Bydefault, inject breadcrumb on page
- In page metadata, add a property, say "noBreadcrumb=true", if this metaproperty exists, do not render breadcrumb.

Also, we should be mindful of page shifts while implementing dynamic breadcrumbs.

**Comment by sdmcraft** [comment]
if home page is the only page without breadcrumbs, we can just not show breadcrumbs for them by looking at the path and realizing that its the home page (this logic should also include language roots). If there are cases beyond just the home page where breadcrumbs are not to be shown, the `noBreadcrumb` metadata sounds good.

**Comment by jindaliiita** [comment]
Yes, noBreadcrumb=true would be a good option
