### ISSUE TITLE
Text block - muted text does not work with p tag

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/sunstar#307]
p tag is added by default, but muted variation does not work with p tag
<img width="1673" alt="image" src="https://github.com/hlxsites/sunstar/assets/129100763/d892021a-cb92-4102-b59b-31881bb7cc6b">

Changes needed

- Handle muted version with p tag also
- Change font size from small to xSmall

**Comment by ehrro** [comment]
Hello Mohit since you are working on this issue can you please add an additional variant to the text block called (text-small) which would be 12px (0.075rem)? Than you.

**Comment by mkbansal1** [comment]
@ehrro I have added text-small variation, and raised PR: https://github.com/hlxsites/sunstar/pull/328

It looks like:
<img width="767" alt="image" src="https://github.com/hlxsites/sunstar/assets/129100763/fae4f586-3623-4460-9d03-f8eb76cec15a">

<img width="679" alt="image" src="https://github.com/hlxsites/sunstar/assets/129100763/8025359d-c376-42d3-82ad-b73b99ec9820">

**Comment by ehrro** [comment]
Thank you @mkbansal1 :)
