### ISSUE TITLE
New block variant with background image

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#317]
We need a block variant for the below us case:

![image](https://github.com/hlxsites/sunstar/assets/1226479/f48bca8e-4491-474d-b8ef-faf419cc7465)

A block with background image that can contain html.

https://main--sunstar--hlxsites.hlx.live/jp/sustainability/s-management/philosophy

**Comment by sdmcraft** [comment]
@ehrro , I am working on a section with background image support in #297 . Likely it may help to address this time of requirement as well.

**Comment by sdmcraft** [comment]
@ehrro , the background image support for sections has been added and [documented here](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/sections&index=13). Please see if it solves your use case.

**Comment by sdmcraft** [comment]
Marking this as resolved. Please feel free to reopen with details as needed.
