### ISSUE TITLE
New table variant or variants for sustainability pages

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#318]
Hello we need this table variant for sustainability pages:

1. This one is a single header row with 1 light grey column
![image](https://github.com/hlxsites/sunstar/assets/1226479/6f7c886f-ce65-4c8f-889a-64e83108524a)

2. This one is standard table with 1 light grey column
![image](https://github.com/hlxsites/sunstar/assets/1226479/26580aaf-75e0-437a-bb14-c6531459c4cd)

https://main--sunstar--hlxsites.hlx.live/jp/sustainability/environment/management
https://main--sunstar--hlxsites.hlx.live/jp/sustainability/environment/products

@sdmcraft

**Comment by JiangLong2019** [comment]
Hi @ehrro, I've made some changes, can you please check the tables on the following pages.

https://table-highlight-column--sunstar--hlxsites.hlx.page/_drafts/jiang/management
https://table-highlight-column--sunstar--hlxsites.hlx.page/_drafts/jiang/products
