### ISSUE TITLE
Substitute Sunstar logo image for broken image links

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/sunstar#326]
@ehrro could you share a logo image which can be used here?

**Comment by ehrro** [comment]
https://www.sunstar.com/wp-content/uploads/2022/04/SUNSTAR-logo.png

**Comment by ehrro** [comment]
Sorry for late reply on this.

**Comment by meejain** [comment]
If I go into the query index - and check its entry I do see the below link listed under image - https://sunstar.com/default-meta-image.png?width=1200&format=pjpg&optimize=medium

There is no metadata for image in the block and hence may be a default image is exported as og:image for all such pages which is not working. 

AFAIK - if there is no image found in metadata or in the content, the fallback logic is to use the default-meta-image.png which has to be in GitHub. so there's no need to bulk-upate those, just add the file to your main branch.

Alternatively, you could set a default image URL for /newsroom/* in the bulk metadata sheet. articles without an image in the metadata block will inherit it. see https://main--helix-website--adobe.hlx.live/docs/bulk-metadata

**Comment by sdmcraft** [comment]
I uploaded the Sunstar logo image provided here in Sharepoint, so the links pointing to it should work
https://main--sunstar--hlxsites.hlx.page/default-meta-image.png?width=1200&format=pjpg&optimize=medium

**Comment by sdmcraft** [comment]
@meejain , thank for checking. Marking this as resolved.
