### ISSUE TITLE
Refactor image-collage block to support 3 types of icon lists

### ISSUE THREAD

**Issue by JiangLong2019** [hlxsites/sunstar#329]
1. `Icon-caption` variation
Mobile:
<img width="406" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/18aa024c-4d43-47e6-a9a9-e5048353a7fd">

Tablet:
<img width="710" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/b1b9665d-2258-4590-bc55-ac4651b363cd">

Desktop:
<img width="1200" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/c7480889-dcf7-42b2-bced-8eaa63cbea4d">

2. `Icon-title-text` variation

Mobile:
<img width="420" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/f126cdd8-0571-4c24-9085-46e16fc9939c">

Tablet:
<img width="940" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/f3ac5277-f137-4c27-a5b3-d0d160de5dc4">

Desktop:
<img width="1235" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/f1c8917b-caff-4cc7-9bfe-0a7e4f4b7674">

3. `Icon-title-list` variation

Mobile:
<img width="428" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/1111072f-0cb2-4568-8d5e-4ee843ecb5b7">

Tablet:
<img width="942" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/866f22e6-8d98-4cfc-8440-ea159fe66297">

Desktop:
<img width="1269" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/0c613b39-ef3e-428e-915f-8b534c70b038">

**Comment by dnbute** [comment]
Just an idea but could this be implemented using the `immage-collage` block?

**Comment by JiangLong2019** [comment]
@dnbute Haha, you found it. Actually, I'm thinking the same thing. Let me change the title.
