### ISSUE TITLE
Add a mechanism to notify viewport size change

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/sunstar#332]
**Current Situation**
At some places in code, we rely on the viewport size. Couple of examples I know are:

- Nav
- Section with backgrounds

Currently either one has to implement this on case-by-case basis (like nav does already) or rely on users to manually refresh the page to rerun the JS after viewport change.

**Proposed Solution**
Have a generic event dispatch and subscribe mechanism to dispatch events on viewport change across tablet, mobile, desktop  and listeners can subscribe to it and handle it appropriately. 

**Important Note**
This has to be done in an efficient way to avoid overhead of viewport resize listeners. Check the impl for `nav` which uses `window.matchMedia` [here](https://github.com/hlxsites/sunstar/blob/5334e432ecf17603f55aaef8b1907cbfe4bffda5/blocks/header/header.js#L194-L221)

**Comment by dnbute** [comment]
Right now I think that if an user flips his phone, the page will not necessarily render correctly, this issue would also help with this case probably

**Comment by shrotia** [comment]
PR raised: https://github.com/hlxsites/sunstar/pull/517
