### ISSUE TITLE
Column block - enhancement for sustainability pages

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/sunstar#345]
1. Add variation - Allow columns to be top-aligned
2. Add variation - Add underline to headings
![image](https://github.com/hlxsites/sunstar/assets/129100763/49539a59-2562-49b5-b50d-996fa20afc33)

3. Add variation - Medium Margin b/w columns (4rem)

**Comment by ehrro** [comment]
Hello @mkbansal1 

I already created the variation for top aligned it's called "flex-start".

And the other 2 already exist. I will find you the names later.

Thanks & best regards,
Dejan Eric

**Comment by mkbansal1** [comment]
Thank you @ehrro , I will use flex-start, though i am making some adjustment around it (removing padding from text)

For border-bottom, i can see history and plain-link, but both are binded with specific usecases, and cant be used for this variation. I have added a more generic variation.
Please check my changes in PR https://github.com/hlxsites/sunstar/pull/351

**Comment by ehrro** [comment]
Hello @mkbansal1 yes. It would be good to remove the padding on Desktop view but keep it on Mobile view.

**Comment by mkbansal1** [comment]
@ehrro Left padding is derived from Section. Please see and confirm if you are aligned with it
https://345-column-block-enhancement--sunstar--hlxsites.hlx.live/sustainability/environment/climate-resource-waste

![image](https://github.com/hlxsites/sunstar/assets/129100763/6b72546d-7503-49ff-abf5-b72be5b4c459)

**Comment by ehrro** [comment]
I think the padding is put on narrow and not the section (which should be the case but we have exceptions). For example homepage. We need to have the padding on the column unless it's inside a narrow and narrower container: 
![image](https://github.com/hlxsites/sunstar/assets/1226479/5ca3b190-9253-40e0-846f-9355c5da336f)
