### ISSUE TITLE
Enclose text with p tag

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#367]
Hello @sdmcraft we have discussed about this earlier. Can you please make sure to enclose the text with p tags when there is only one paragraph in the word document? This would simplify prevent us adding a lot of css for no reasons. Thank you.

https://main--sunstar--hlxsites.hlx.page/about/chairman-interview

![image](https://github.com/hlxsites/sunstar/assets/1226479/c56e96c1-1081-415b-b712-92daf22700f7)

**Comment by sdmcraft** [comment]
@rrrragas , can you please help with this one?
