### ISSUE TITLE
Add support for box placement inside with-background-image block

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#368]
Hello I would to add support to place the content box in 9 different position.

1. top-left
2. top-center
3. top-right
4. middle-left
5. middle-center
6. middle-right
7. bottom-left
8. bottom-center
9. bottom-right

![image](https://github.com/hlxsites/sunstar/assets/1226479/1960d590-5abc-4dc5-92cd-b5a483b30509)

@sdmcraft

**Comment by ehrro** [comment]
Update I don't think we need the center options. and the middle options.

So please only keep:

1. top-left
2. top-right
3. bottom-left
4. bottom-right

![image](https://github.com/hlxsites/sunstar/assets/1226479/6313f62f-7643-4d5a-8b0b-0de7b63b0dc0)

**Comment by sdmcraft** [comment]
@ehrro , could you review various variations that we have for the hero banner with text overlap in the [block library](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/hero-banner&index=6)? I think they handle most of the use cases already.

![image](https://github.com/hlxsites/sunstar/assets/1191451/9fe44c96-3fad-4fa7-a38a-c820f1f363e1)
