### ISSUE TITLE
Back Button Component for social pages

### ISSUE THREAD

**Issue by hparwani2** [hlxsites/sunstar#369]
https://www.sunstar.com/sustainability/social/community/

![Uploading Screenshot 2023-11-15 at 7.56.47 AM.png…]()

**Comment by sdmcraft** [comment]
Likely this is no longer needed, Already done here https://main--sunstar--hlxsites.hlx.page/sustainability/environment/data

**Comment by sdmcraft** [comment]
Closing this issue. @hparwani2 , I this is still needed, please feel free to reopen with details.
