### ISSUE TITLE
Native Image Size variant on columns doesn't work

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#378]
The Native image size variant for columns block should render the image its original size but it doesn't work.

https://main--sunstar--hlxsites.hlx.page/jp/newsroom/20221003

![image](https://github.com/hlxsites/sunstar/assets/1226479/4187f0cf-0e2e-40bf-bea1-3302de3b028a)
![image](https://github.com/hlxsites/sunstar/assets/1226479/5cd3c9f8-1c28-48d5-b9e8-add3da13547c)

@sdmcraft

**Comment by sdmcraft** [comment]
@RitwikSrivastava can you please take a look at this?

**Comment by RitwikSrivastava** [comment]
> @RitwikSrivastava can you please take a look at this?

Sure. I will work on this.
