### ISSUE TITLE
Unable to edit a specific news. File looks corrupt

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#379]
https://main--sunstar--hlxsites.hlx.live/jp/newsroom/20220722

![image](https://github.com/hlxsites/sunstar/assets/1226479/3bf148bc-3810-4b4d-b7c7-32e847fd3448)

**Comment by jindaliiita** [comment]
Tried to reimport this also but again its getting corrupted.
I have manually added the file content as of now.
@ehrro Kindly check
