### ISSUE TITLE
FOUC on pages

### ISSUE THREAD

**Issue by jindaliiita** [hlxsites/sunstar#383]
Experiencing FOUC on some pages.

![Uploading Screenshot 2023-11-16 at 11.48.39 AM.png…]()

**Comment by sdmcraft** [comment]
As [discussed here](https://discord.com/channels/1131492224371277874/1144495462255185971/1174672445387583558), this seems to be a sidekick issue. @jindaliiita , could you please open an issue in https://github.com/adobe/helix-sidekick-extension/issues

**Comment by jindaliiita** [comment]
Yes
Opened one https://github.com/adobe/helix-sidekick-extension/issues/607
