### ISSUE TITLE
Healthy thinking highlighted big articles disappeared 

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#387]
It looks like the big highlighted articles for each category disappeared: 

Edge delivery:
![image](https://github.com/hlxsites/sunstar/assets/1226479/9ef969a5-acb6-4d3b-a34a-413f7079dbb4)

Current:
![image](https://github.com/hlxsites/sunstar/assets/1226479/e2ff15bd-af1c-4970-9a94-c2df16998dc9)

@sdmcraft

**Comment by sdmcraft** [comment]
@meejain , can you please take a look at this? I am wondering if this could be related to the recent changes we made in the `highlight` block for `newsroom` page.
