### ISSUE TITLE
Add Header

### ISSUE THREAD

**Issue by jindaliiita** [hlxsites/sunstar#4]
Refer - https://www.sunstar.com/

- [x] #37
- [x] #38
- [x] #39
- [x] #40

**Comment by jindaliiita** [comment]
Himanshu Parwani Kindly pick this

**Comment by jindaliiita** [comment]
@hparwani2 If you feel you can split this issue in multiple sub issues.

**Comment by hparwani2** [comment]
- [ ] subtask-1: Header top and middle nav
- [ ] subtask-2: Header top and middle nav - mobile version
- [ ] subtask-3: add bottom nav
- [ ] subtask-4: add bottom nav - mobile version
