### ISSUE TITLE
Table Bock : highlight-first-column Variant

### ISSUE THREAD

**Issue by shrotia** [hlxsites/sunstar#407]
Highlight First Column variant has an issue when Cells are merged. Here is the detailed description: https://github.com/hlxsites/sunstar/pull/406/files#r1398804210
Impacted Page: https://main--sunstar--hlxsites.hlx.live/sustainability/environment/products

Potential Solution:  add class=`highlight-first-column` through javascript considering "rowspan" attribute.

**Comment by JiangLong2019** [comment]
Hey @shrotia, I got this ticket last week and seems it's similar to your case. Can you please check if it can fix your issue as well? BTW, it has not been merged since I'm waiting for Dejan's response

**Comment by shrotia** [comment]
> Hey @shrotia, I got this ticket last week and seems it's similar to your case. Can you please check if it can fix your issue as well? BTW, it has not been merged since I'm waiting for Dejan's response
> 
> #318

Yes, it seems fixed with your changes.

https://table-highlight-column--sunstar--hlxsites.hlx.page/sustainability/environment/products
<img width="783" alt="image" src="https://github.com/hlxsites/sunstar/assets/119420493/778bdefd-f0d3-4052-b4f0-c22d291a72a0">

**Comment by shrotia** [comment]
Duplicate of https://github.com/hlxsites/sunstar/issues/318
