### ISSUE TITLE
SEO and Accessibility issue in header

### ISSUE THREAD

**Issue by jindaliiita** [hlxsites/sunstar#412]
<img width="1728" alt="Screenshot 2023-11-20 at 11 11 33 PM" src="https://github.com/hlxsites/sunstar/assets/12638407/42676ad1-1d5b-43fa-a2a8-97b1fe89df0c">
<img width="1728" alt="Screenshot 2023-11-20 at 11 12 25 PM" src="https://github.com/hlxsites/sunstar/assets/12638407/60837b9c-dc2b-4187-987a-68458497a569">

**Comment by hparwani2** [comment]
part 2 isn't related to header, it is related to the heading entered in columns block for **id=for-consumer** should be h5 or h4 instead of h6 as it is greater than the **About us** in footer section, which is h5,
SEO related issues has been fixed in https://github.com/hlxsites/sunstar/pull/451
