### ISSUE TITLE
Center absolute section container for background variants

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#437]
Hello @sdmcraft 

Can you please implement the following:

When we use the bg-image full width container we should be able to specify the container size (narrow, narrower etc) but still have it centered.

![image](https://github.com/hlxsites/sunstar/assets/1226479/88fe6ed3-ac57-4b3f-9859-56df9dfa3ca4)

I believe we just need to add right: 0 to the container and this should do the trick but it needs to have the same logic when we choose narrow or narrower styles.

Thanks.

**Comment by dnbute** [comment]
Hi @ehrro, I merged a PR recently that should have fixed this, could you check?

**Comment by ehrro** [comment]
Hello @dnbute how can I check this:
![image](https://github.com/hlxsites/sunstar/assets/1226479/85feeafc-3d79-486a-a7b9-b415530ce7f1)

Thanks.
