### ISSUE TITLE
Career and career children page mobile menu doesn't work

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#441]
![image](https://github.com/hlxsites/sunstar/assets/1226479/4d9a3580-953b-483c-9127-bbcc1d2ef4c4)

![image](https://github.com/hlxsites/sunstar/assets/1226479/2621d460-1e75-42b0-9cec-a5ab0f11fb93)
![image](https://github.com/hlxsites/sunstar/assets/1226479/7c15d6af-c3a8-4afe-89e5-f29c302f6a75)

@sdmcraft

**Comment by sdmcraft** [comment]
Looks like presence of career carousel on this page causes this If its removed, the problem is resolved. @bosschaert , could you please check since you have insights on career-carousel block.
