### ISSUE TITLE
Extra split variant for columns

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#448]
Can you please create a split 2/3 and 3/2 for columns block?

@bosschaert

**Comment by dnbute** [comment]
Hi @ehrro, we have this
```
 --split-firstthird: 34%:66%;
  --split-lastthird: 66%:34%;
 ```
I'm not sure if this is what you meant

**Comment by ehrro** [comment]
Hello @dnbute 
I need this one :
--split-firsttwothird: 40%:60%;
--split-lasttwothird: 60%:60%;

In addition to that I noticed that the about us columns have a wider gap in between. Instead of targeting the wider gap on the about us page can you please create a variant for wider gap and we will add them manually to the columns we want?

Thanks.
