### ISSUE TITLE
Automatically cut cards title with css

### ISSUE THREAD

**Issue by JiangLong2019** [hlxsites/sunstar#453]
Feedback from the customer in [excel](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B15EAEB2A-C831-4779-922B-6EC0F4E36CD6%7D&file=sunstar_com-crawl-report.xlsx&action=default&mobileredirect=true) No.109

**Comment by sdmcraft** [comment]
@JiangLong2019 , @robwozniak , could you please review if something is to be done here? Maybe add some more details and screenshots explaining the issue.

**Comment by JiangLong2019** [comment]
Hi @robwozniak, this issue is related to your following comments on https://www.sunstar.com/healthy-thinking/category/lets-talk-oral-health page. Could you suggest if we need to make the change or keep it as is?

>looks fine but I am not sure if we want cut tiles' heading, todo: confirm; I would consider `object-position: center;` for pictures on mobile

**Comment by robwozniak** [comment]
Hi @JiangLong2019 @sdmcraft 

I can no longer see the tiles on this page - https://main--sunstar--hlxsites.hlx.live/healthy-thinking/lets-talk-oral-health, but as far as I can remember there was a mechanism to add dots and trim the heading to a certain length.

This suggestion with `object-position: center` was probably due to the fact that images were oddly positioned on mobile phones.

**Comment by JiangLong2019** [comment]
@robwozniak thanks for the chating.

>I can no longer see the tiles on this page - https://main--sunstar--hlxsites.hlx.live/healthy-thinking/lets-talk-oral-health, but as far as I can remember there was a mechanism to add dots and trim the heading to a certain length.

Yes, we can use `text-overflow` to cut the words automatically. One thing needs your confirmation,  do you have any suggestions on how many lines we should show?

Ex. 
2 lines:
<img width="382" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/644d8678-ec84-4290-ac74-edb2736fae7b">

3 lines:
<img width="381" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/7d8d0f71-8a76-4866-b989-962c40002e97">


>This suggestion with object-position: center was probably due to the fact that images were oddly positioned on mobile phones.

Good to know that this is no longer an issue now, we will ignore it.

**Comment by robwozniak** [comment]
@ehrro can you advise while I am not sure how much you want to change it. As far as I can see JS is being used to crop the title - https://github.com/sunstar-global/sunstar/blob/main/blocks/cards/cards.js#L53 . 

This `text-overflow` solution mentioned by Jiang (with crop removal from cards component) seems to be a nice solution, while css will hide it visually, but content will normally be visible to seo robots in source code - now being cropped.

**Comment by JiangLong2019** [comment]
Confirmed with Dejan in standup meeting, we will do the 3 lines design.
