### ISSUE TITLE
History page

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#457]
I noticed a small issue with the TOC block after we updated the section class css.

![image](https://github.com/hlxsites/sunstar/assets/1226479/f16959ed-afb9-4724-9837-ba4625ac3a25)

Can you please just add box-sizing: border-box to fix it?

@dnbute @sdmcraft

**Comment by shrotia** [comment]
It would be ideal to have the `box-sizing: border-box` property set globally at the page level. However, I'm uncertain why it wasn't implemented initially. I'm just looking into whether there's any historical context or reasoning behind this decision.

BTW raised both the PRs.
local : https://github.com/hlxsites/sunstar/pull/459
global: https://github.com/hlxsites/sunstar/pull/459

**Comment by dnbute** [comment]
I think we just missed adding this at the beginning, I honestly thought we had this already, I think it should be fine if we add this globally but let's check to make sure

**Comment by shrotia** [comment]
@dnbute @ehrro We are going ahead with merging the Global one: https://github.com/hlxsites/sunstar/pull/459

Please let me know if you see any concern.

**Comment by shrotia** [comment]
Fixed through https://github.com/hlxsites/sunstar/pull/459
