### ISSUE TITLE
Hero banner overlap regression 

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#483]
I noticed regression for hero banner overlap after box-sizing border box was applied globally.

![image](https://github.com/hlxsites/sunstar/assets/1226479/270396bd-f5dd-47a5-a99e-acd509696d2b)

Here is the corrected width and height.

Make sure to apply it to all variants of the block.

.hero-banner.overlap .hero-banner-text-container {
    padding: 10rem 3.75rem 0;
    width: 35rem;
    height: 43.75rem;
}

@sdmcraft @shrotia

**Comment by ehrro** [comment]
Same here: 

![image](https://github.com/hlxsites/sunstar/assets/1226479/37c6f193-5c8e-45ac-b6a1-788e0f9aee4f)

**Comment by dnbute** [comment]
As a rule of thumb, we just need to add the padding and margin to the height value and it should be fine whenever we see a case like this

**Comment by ehrro** [comment]
Done by @dnbute
