### ISSUE TITLE
Hero with image and text

### ISSUE THREAD

**Issue by JiangLong2019** [hlxsites/sunstar#50]
A common hero which covers following pages' requirements.

1. https://www.sunstar.com/healthy-thinking/

<img width="612" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/ebbf2718-85ff-401e-bd2d-a956f82545f0">

2. https://www.sunstar.com/sustainability/

<img width="612" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/5fd8e41c-dc20-471f-aa0d-59c6b81a1dc5">

3. https://www.sunstar.com/about/
<img width="612" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/82a8a515-6d65-4079-b229-2c4afe8df87e">

4. https://www.sunstar.com/healthy-thinking-report/oral-survey-2021/
<img width="612" alt="image" src="https://github.com/hlxsites/sunstar/assets/57093988/c1f46fe4-2f43-4d93-b14f-1d30bd48ff08">

**Comment by dnbute** [comment]
@JiangLong2019 I think we've covered these cases, could we close this issue?

**Comment by JiangLong2019** [comment]
Close it.
