### ISSUE TITLE
Icons missing for some reasons

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#512]
Icons not showing anymore https://main--sunstar--hlxsites.hlx.live/research

![image](https://github.com/hlxsites/sunstar/assets/1226479/f978f5a8-b18c-48b4-867b-b801b11be956)

![image](https://github.com/hlxsites/sunstar/assets/1226479/e59f16b1-65c9-4747-bd0f-9898512f7729)

@sdmcraft

**Comment by JiangLong2019** [comment]
@sdmcraft Seems it's related to #502, shall we rollback it?
