### ISSUE TITLE
Table variant

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#514]
Is it possible to create a table variant with
1. The first column set to 30%
2. Where we can align the text in word and it will be automatically aligned in the element itself. element.style { vertical-align: top etc.. } We have some use case where the text is aligned in the center some on the left etc..
3. Have 2 padding variant for td (2rem and 1rem)
4. Native image size

![image](https://github.com/hlxsites/sunstar/assets/1226479/1e97f858-9753-4ac0-bd07-3cbd87519a6b)

Let me know if you need more information about this request or if it's not clear but ideally I want to cover this use case:
https://www.sunstar.com/jp/sustainability/s-management/materiality/

@sdmcraft

**Comment by JiangLong2019** [comment]
@ehrro About requirement No.2, I need to confirm with you.
>Where we can align the text in word and it will be automatically aligned in the element itself. element.style { vertical-align: top etc.. } We have some use case where the text is aligned in the center some on the left etc..


First, the table is automatic expansion in height, I think vertical-align doesn't work in this case.
Second, as far as I know, `text-align` is not available in SharePoint online word table for authoring. We can add the following variants instead which are not able to affect specific td, it will impact all td cells except the first column ones. 
- text-align-left
- text-align-center
- text-align-right

Easily I implemented a version with above function, you can have a try. Please let me know your thoughts.
https://table-variant--sunstar--hlxsites.hlx.page/jp/sustainability/s-management/materiality-beta

**Comment by ehrro** [comment]
Hello @JiangLong2019 understood. No worries. I thought it was possible to do the same as for the columns with the alignments.

Thank you.

**Comment by ehrro** [comment]
You can push the changes to main it looks perfect.

**Comment by JiangLong2019** [comment]
@ehrro Thanks for your confirmation! I will check if there are any impact to authored pages and commit the PR.
