### ISSUE TITLE
Newsroom page > News category select, text color white for the options

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#532]
Hello can you please set the text of the options in blue
![image](https://github.com/hlxsites/sunstar/assets/1226479/48b22ffc-33d9-4cea-8146-536194ca1bf2)

Like for the "year" select:
![image](https://github.com/hlxsites/sunstar/assets/1226479/6adcae5c-5edd-40ab-83fd-bc280962c478)

Thanks

@sdmcraft

**Comment by shrotia** [comment]
Hi @ehrro , I have added Category Titles, but look and feel is different (not Blue).

<img width="1074" alt="image" src="https://github.com/hlxsites/sunstar/assets/119420493/5207eb44-5b8d-4ccd-adc1-0afe480a1281">

<img width="811" alt="image" src="https://github.com/hlxsites/sunstar/assets/119420493/4e2bf3f6-5a05-45c8-b276-c48d7bc5fe33">

I see same look & feel on the original site as well.
<img width="996" alt="image" src="https://github.com/hlxsites/sunstar/assets/119420493/456cb39b-9862-4f45-a206-5d42ec5a59f7">

Please confirm f we should match the Blue look & feel as well?

**Comment by ehrro** [comment]
sorry not an issue.
