### ISSUE TITLE
Research Literature Page spacing issue

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#546]
I noticed that there is only spacing on the last tab's content:

First tab:
![image](https://github.com/hlxsites/sunstar/assets/1226479/49db8038-eb85-4228-81cd-f77cb63288ba)

Last tab:
![image](https://github.com/hlxsites/sunstar/assets/1226479/23ef3cce-2836-49ad-91c6-d5f7761cb7c5)

@sdmcraft

**Comment by sdmcraft** [comment]
@ehrro , this has been resolved via #547 and you may want to update your fork with the latest from the main branch in this repo. Additionally, you'd have to update the Word docs which are using the `static` section and add `padded` style to them. 

<img width="731" alt="image" src="https://github.com/hlxsites/sunstar/assets/1191451/fdf09bf5-f5ed-40cb-a008-2ab4e84ef5ca">

This is there on the research/literature pages (both en and jp)
