### ISSUE TITLE
Every page flickers after a few seconds

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/sunstar#6]
A few seconds after a page is loaded it flickers, just before the 'consent fingerprint' appears in the bottom left corner. See video:

https://github.com/hlxsites/sunstar/assets/226514/d9023a3e-04e3-4830-a1b9-3e6935671f01

**Comment by bosschaert** [comment]
Looking a little deeper into it with (@karlpauls - thanks Karl!) the issue happens in the `loadAdobeLaunch()` method here: https://github.com/hlxsites/sunstar/blob/049ce5044fbc5d8af1194d5a33a5a5d09e5db4e1/scripts/delayed.js#L9

This ultimately sets the opacity of the `body` to `0` for a while which causes the flickering. This is a feature of Adobe Target which doesn't work well with the delayed loading of pages. It's described here: https://experienceleague.adobe.com/docs/target-dev/developer/client-side/at-js-implementation/at-js/manage-flicker-with-atjs.html?lang=en
The page also suggests an alternative for asynchronous loading of pages, which probably needs to be configured in Target.

**Comment by jindaliiita** [comment]
@bosschaert Is this happening on .live domain also ?

**Comment by bosschaert** [comment]
@hparwani2 thanks for the link. I have added the snippet:

```
window.targetGlobalSettings = {
  bodyHidingEnabled: false,
};
```

to the `delayed.js` file as suggested in that slack message. However the flickering is still there. Maybe it's a little bit shorter, but it's definitely there, see here: https://issue-6--sunstar--hlxsites.hlx.page/career/boedi-hartono

**Comment by hparwani2** [comment]
you can this fix:
https://github.com/hlxsites/nedbank/commit/987f43ffef438df61ee70a431ec5bd0d5bcb69e6
